name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch: # enable manual execution

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['9.6.4']
        os: [ubuntu-latest]
        resolver: [lts-22]

    name: ${{ matrix.resolver }} (${{ matrix.ghc }})
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Restore from cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            ~/.ghcup
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack${{ matrix.resolver }}

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true

      - name: Versions
        run: |
          stack --version
          cabal --version
          ghc   --version

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        timeout-minutes: 15
        run: |
          stack build --resolver ${{ matrix.resolver }} --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Run tests with coverage
        timeout-minutes: 15
        run: |
          stack test --resolver ${{ matrix.resolver }} --system-ghc --test --coverage --fast

      - name: Package list
        run: |
          stack --resolver ${{ matrix.resolver }} exec ghc-pkg list || true

      - name: Generate coverage report
        uses: 8c6794b6/hpc-codecov-action@v3
        with:
          target: stack:jsonld-test
          out: ./codecov.json
          verbose: true

      - name: Send coverage report
        uses: codecov/codecov-action@v3
        with:
          files: ./codecov.json
          fail_ci_if_error: false # optional (default = false)
          verbose: true
